"""
Automated PDF Report Generation
"""

import streamlit as st
from reportlab.lib.pagesizes import letter, A4
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image, PageBreak
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from datetime import datetime
import io

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#1a1a2e'),
            spaceAfter=30,
            alignment=TA_CENTER
        )
    
    def generate_pdf_report(self, data, report_type="comprehensive"):
        """
        Generate professional PDF report
        """
        buffer = io.BytesIO()
        
        doc = SimpleDocTemplate(
            buffer,
            pagesize=letter,
            rightMargin=72,
            leftMargin=72,
            topMargin=72,
            bottomMargin=18
        )
        
        story = []
        
        # Title
        title = Paragraph("Water Quality Assessment Report", self.title_style)
        story.append(title)
        story.append(Spacer(1, 12))
        
        # Metadata
        meta_data = [
            ['Report Generated:', datetime.now().strftime("%Y-%m-%d %H:%M:%S")],
            ['Report Type:', report_type.title()],
            ['Generated By:', data.get('user', 'System')],
            ['Location:', data.get('location', 'Multiple Sites')]
        ]
        
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (-1, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, -1), 10),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(meta_table)
        story.append(Spacer(1, 20))
        
        # Executive Summary
        story.append(Paragraph("Executive Summary", self.styles['Heading2']))
        story.append(Spacer(1, 12))
        
        summary_text = f"""
        Water Quality Index: {data.get('wqi', 'N/A')}<br/>
        Classification: {data.get('classification', 'N/A')}<br/>
        Microplastic Count: {data.get('mp_count', 'N/A')} particles/L<br/>
        Dissolved Oxygen: {data.get('do', 'N/A')} mg/L<br/>
        Overall Status: {data.get('status', 'Under Assessment')}
        """
        
        story.append(Paragraph(summary_text, self.styles['Normal']))
        story.append(Spacer(1, 20))
        
        # Key Findings
        story.append(Paragraph("Key Findings", self.styles['Heading2']))
        story.append(Spacer(1, 12))
        
        findings_data = [
            ['Parameter', 'Value', 'Status', 'Threshold'],
            ['WQI', str(data.get('wqi', '-')), data.get('wqi_status', '-'), '> 50'],
            ['DO', f"{data.get('do', '-')} mg/L", data.get('do_status', '-'), '> 4.0'],
            ['Microplastic', f"{data.get('mp_count', '-')} p/L", data.get('mp_status', '-'), '< 100'],
            ['Turbidity', f"{data.get('turbidity', '-')} NTU", data.get('turb_status', '-'), '< 50']
        ]
        
        findings_table = Table(findings_data, colWidths=[1.5*inch, 1.5*inch, 1.5*inch, 1.5*inch])
        findings_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        
        story.append(findings_table)
        story.append(Spacer(1, 20))
        
        # Recommendations
        story.append(Paragraph("Recommendations", self.styles['Heading2']))
        story.append(Spacer(1, 12))
        
        recommendations = data.get('recommendations', [
            'Continue regular monitoring',
            'Implement pollution control measures',
            'Increase public awareness campaigns'
        ])
        
        for rec in recommendations:
            story.append(Paragraph(f"• {rec}", self.styles['Normal']))
            story.append(Spacer(1, 6))
        
        # Build PDF
        doc.build(story)
        
        buffer.seek(0)
        return buffer
    
    def show_interface(self):
        """
        Streamlit interface for report generation
        """
        st.subheader("📄 Generate Reports")
        
        col1, col2 = st.columns(2)
        
        with col1:
            report_type = st.selectbox(
                "Report Type",
                ["Comprehensive", "Executive Summary", "Technical Details", "Compliance Report"]
            )
        
        with col2:
            location = st.selectbox(
                "Location",
                ["All Sites", "Delhi - Yamuna", "Mumbai - Mithi", "Chennai - Cooum"]
            )
        
        # Sample data (in production, get from actual measurements)
        report_data = {
            'user': st.session_state.get('name', 'System'),
            'location': location,
            'wqi': 45.2,
            'classification': 'Fair',
            'mp_count': 120,
            'do': 5.2,
            'turbidity': 52,
            'status': 'Requires Attention',
            'wqi_status': '⚠️ Below Target',
            'do_status': '✅ Acceptable',
            'mp_status': '⚠️ Elevated',
            'turb_status': '⚠️ High',
            'recommendations': [
                'Increase cleanup frequency to weekly',
                'Investigate upstream pollution sources',
                'Deploy additional monitoring sensors',
                'Implement stricter discharge regulations'
            ]
        }
        
        if st.button("🎨 Generate PDF Report", type="primary"):
            with st.spinner("Generating report..."):
                pdf_buffer = self.generate_pdf_report(report_data, report_type.lower())
                
                st.success("✅ Report generated successfully!")
                
                st.download_button(
                    label="📥 Download PDF Report",
                    data=pdf_buffer,
                    file_name=f"water_quality_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf",
                    mime="application/pdf"
                )
        
        st.markdown("---")
        
        # Scheduled reports
        st.markdown("### ⏰ Schedule Automated Reports")
        
        col1, col2, col3 = st.columns(3)
        
        with col1:
            frequency = st.selectbox("Frequency", ["Daily", "Weekly", "Monthly"])
        
        with col2:
            time = st.time_input("Time")
        
        with col3:
            recipients = st.text_input("Email Recipients", "admin@example.com")
        
        if st.button("💾 Save Schedule"):
            st.success(f"✅ Scheduled {frequency.lower()} reports at {time}")